version: '3.6'
services:
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
  app:
    image: vk-gpt-bot:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
volumes:
  redis_data:
